#!/bin/bash

build_variant()
{
    VARIANT=$1
    qmake -config release "CONFIG += release_macos build_${VARIANT}"
    make clean
    make -j8
    rm -rf build/macos/obj
    cd build/macos
    APP=$(ls | grep vesc_tool | grep .app)
    if [ -z "${APP}" ]; then
        echo "error: Mac app not found"
        exit 1
    fi
    zip -r vesc_tool_${VARIANT}_macos.zip "${APP}"
    ls | grep -v '\.zip$' | xargs rm -rf
    cd ../..
}

build_variants()
{
    set -e

    VARIANTS="original platinum gold silver bronze free"

    rm -rf build/macos/*

    for VARIANT in ${VARIANTS}; do
        echo "Building ${VARIANT}"
        build_variant ${VARIANT}
    done
}

QMAKE=$(which qmake)

if [ -z "${QMAKE}" ]; then
  echo "error: Qt not found. Install with Brew."
  echo "brew install qt"
  exit 1
else
  build_variants
fi
